macos_titlebar_color              background

foreground                        #F7EEF2
background                        #181818
selection_foreground              #181818
selection_background              #F0D1E0
cursor                            #F7EEF2
url_color                         #C6DDFF
active_border_color               #C6DDFF
inactive_border_color             #C4B2BC
active_tab_foreground             #181818
active_tab_background             #C6DDFF
inactive_tab_foreground           #E1C6D4
inactive_tab_background           #8F6C7D
color0                            #55414D
color8                            #C6B7C0
color1                            #BBD9FF
color9                            #D2E8FF
color2                            #D0B9DC
color10                           #E4CFF0
color3                            #F7BCCF
color11                           #FFD6E1
color4                            #C6C6F2
color12                           #DFDFFF
color5                            #C4DCFF
color13                           #D9EAFF
color6                            #F3D0E2
color14                           #FFE3EF
color7                            #F7EEF2
color15                           #FFF9FB
