# vim:ft=kitty

## name: Mono Plus
## author: Eemil
## based on: ../nvim/colors/mono_plus.lua

background #090909
foreground #d0cece

selection_background #403a3a
selection_foreground #ffffff

cursor #e2e0e0
cursor_text_color #141212

url_color #a9c1d0

# Tabs
active_tab_background #d0cece
active_tab_foreground #141212
inactive_tab_background #242121
inactive_tab_foreground #918b8b

# Windows
active_border_color #9db1c4
inactive_border_color #393535

# Restrained ANSI palette with clear separation from the background
color0  #242121
color1  #bd8383
color2  #a4b7a1
color3  #cbb891
color4  #93a8bd
color5  #b7a4b7
color6  #94ada9
color7  #d0cece

# Bright ANSI palette
color8  #7b7676
color9  #d79a9a
color10 #bdd0b9
color11 #dfcba2
color12 #aac1d5
color13 #ccb8cc
color14 #abc4c0
color15 #ffffff

# Extended colors
color16 #dfcba2
color17 #a96666
