# vim:ft=kitty

## name:     E-Ink (Color)
## author:   Algilbert Gomez (https://github.com/alexxGmZ) / Custom E-Ink Accent
## license:  MIT
## upstream: https://github.com/alexxGmZ/e-ink.kitty/blob/main/E-Ink.conf
## blurb:    An e-ink display aesthetic theme with muted, paper-ink accent colors.

foreground #474747
background #CCCCCC
selection_foreground none
selection_background #AEAEAE

cursor none

# black
color0  #303438
color8  #5E6266

# red
color1  #8C3B3B
color9  #9E4D4B

# green
color2  #3E6B48
color10 #5C7C65

# yellow
color3  #7D5B20
color11 #92702E

# blue
color4  #364F6B
color12 #486382

# magenta
color5  #754564
color13 #845277

# cyan
color6  #386B6B
color14 #4B7E80

# white
color7  #474747
color15 #787C80

