# vim:ft=kitty

## name:     E-Ink (Color)
## author:   Algilbert Gomez (https://github.com/alexxGmZ) / Custom E-Ink Accent
## license:  MIT
## upstream: https://github.com/alexxGmZ/e-ink.kitty/blob/main/E-Ink.conf
## blurb:    An e-ink display aesthetic theme with muted, paper-ink accent colors.

macos_titlebar_color background

foreground #3F444A
background #DDDCD8
selection_foreground #383E45
selection_background #CACED3

cursor #3F444A
cursor_text_color #DDDCD8
url_color #667688
active_border_color #B7B8B4
inactive_border_color #C3C4C0

active_tab_foreground #3F444A
active_tab_background #D0CFCC
inactive_tab_foreground #82878D
inactive_tab_background #DDDCD8

# black
color0  #383E45
color8  #757B83

# red
color1  #8B6D74
color9  #A07F88

# green
color2  #617063
color10 #7B8A7C

# yellow
color3  #8A7F6D
color11 #A09380

# blue
color4  #667688
color12 #8091A0

# magenta
color5  #786B7C
color13 #96879A

# cyan
color6  #66776B
color14 #829287

# white
color7  #3F444A
color15 #82878D

