background            #14100c
foreground            #b7ae9f
cursor                #e7dac7
cursor_text_color     #14100c
selection_background  #2a221b
selection_foreground  #e7dac7
url_color             #8ea5b1

active_tab_foreground   #e7dac7
active_tab_background   #14100c
active_tab_font_style   bold
inactive_tab_foreground #60574c
inactive_tab_background #14100c

active_border_color     #8ea5b1
inactive_border_color   #29231d

color0  #14100c
color8  #60574c

color1  #a06d63
color9  #bd8277

color2  #8e9d72
color10 #a5b487

color3  #b4ab73
color11 #cbc387

color4  #7f99ad
color12 #97b1c4

color5  #a48a8f
color13 #bc9fa5

color6  #7f9f9d
color14 #97b8b5

color7  #b7ae9f
color15 #e7dac7
