vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

local set_hl = vim.api.nvim_set_hl

vim.o.background = "dark"
vim.g.colors_name = "vibrant"

--highlight Normal guifg=#D6CFC4 guibg=#101010
set_hl(0, "Normal", { fg = "#D6CFC4", bg = "#0e1415" })
set_hl(0, "StatusLine", { fg = "#D6CFC4", bg = "#101010" })
set_hl(0, "StatusLineNC", { fg = "#D6CFC4", bg = "#202020" })
set_hl(0, "Function", { fg = "#7DADA8" })
set_hl(0, "Title", { fg = "#A8D89E" })
set_hl(0, "Identifier", { fg = "#D6CFC4" })
set_hl(0, "Delimiter", { fg = "#D6CFC4" })
set_hl(0, "Directory", { fg = "#98C98A" })
set_hl(0, "Module", { italic = true })
set_hl(0, "Special", { fg = "#98C98A" })
set_hl(0, "Namespace", { link = "Module" })
set_hl(0, "Type", { fg = "#90C0D0" })
set_hl(0, "Number", { fg = "#8EAAC5" })
set_hl(0, "Float", { link = "Number" })
set_hl(0, "Constructor", { link = "Type" })
set_hl(0, "Character", { link = "String" })
set_hl(0, "Constant", { fg = "#8EAAC5" })
set_hl(0, "Operator", { fg = "#A8D89E" })
set_hl(0, "ColorColumn", { bg = "#0A0A0A" })
set_hl(0, "String", { fg = "#95D095" })
set_hl(0, "Keyword", { fg = "#9CD99C" })
set_hl(0, "@namespace", { link = "Namespace" })
set_hl(0, "@module", { link = "Module" })
set_hl(0, "@module.builtin", { link = "Module" })
set_hl(0, "@string.special.path", { link = "Underlined" })
set_hl(0, "@constructor", { link = "Constructor" })
set_hl(0, "@identifier", { link = "Identifier" })
set_hl(0, "@type.builtin", { link = "@type" })
set_hl(0, "@variable.builtin", { link = "@variable" })
set_hl(0, "@constant.builtin", { link = "@constant" })
set_hl(0, "@function.builtin", { link = "@function" })
set_hl(0, "@tag.attribute", { link = "@attribute" })
set_hl(0, "@keyword.function", { link = "Keyword" })
set_hl(0, "@keyword.operator", { link = "Keyword" })
set_hl(0, "@keyword.return", { link = "Keyword" })
set_hl(0, "@string", { link = "String" })
set_hl(0, "Comment", { fg = "#9B9B7A", italic = true })
set_hl(0, "TodoFgTODO", { fg = "#BED1A8", italic = true })
set_hl(0, "TodoBgTODO", { fg = "#0e1415", bg = "#BED1A8", italic = true })
set_hl(0, "Pmenu", { bg = "#0e1415" })
set_hl(0, "PmenuSel", { bg = "#1D1D1D", fg = "#9CD99C" })
set_hl(0, "PmenuSbar", { bg = "#121212" })
set_hl(0, "PmenuThumb", { bg = "#2A2A2A" })
set_hl(0, "NvimPickerNormal", { fg = "NvimLightGrey2", bg = "#121212" })
set_hl(0, "NvimPickerBorder", { fg = "#2A2A2A", bg = "#121212" })
set_hl(0, "NvimPickerSelected", { fg = "#9CD99C", bg = "#1D1D1D", bold = true })
set_hl(0, "NvimPickerHeader", { fg = "#8AA070", bg = "#121212", bold = true })
set_hl(0, "NvimPickerHeaderBorder", { fg = "#2A2A2A", bg = "#121212" })

-- Floating windows
set_hl(0, "FloatBorder", { fg = "#2A2A2A", bg = "#0e1415" })
set_hl(0, "FloatTitle", { fg = "#8AA070", bg = "#0e1415", bold = true })
set_hl(0, "NormalFloat", { fg = "NvimLightGrey2", bg = "#0e1415" })
set_hl(0, "FloatShadow", { bg = "#050505", blend = 80 })
set_hl(0, "FloatShadowThrough", { bg = "#050505", blend = 100 })

-- Variable and property links
set_hl(0, "@variable.member", { link = "Identifier" })
set_hl(0, "@variable.member.lua", { link = "Identifier" })
set_hl(0, "@property.lua", { link = "Identifier" })
set_hl(0, "@field.lua", { link = "Identifier" })
set_hl(0, "@variable.member.builtin", { fg = "#D6CFC4" })
set_hl(0, "@config", { fg = "#D6CFC4" })
set_hl(0, "@method.call", { link = "Identifier" })
set_hl(0, "@method", { link = "Identifier" })
set_hl(0, "@label.lua", { link = "Identifier" })
set_hl(0, "@variable.builtin", { fg = "#D6CFC4" })
set_hl(0, "@namespace.lua", { fg = "#D6CFC4" })
set_hl(0, "@module.builtin", { fg = "#D6CFC4" })
set_hl(0, "@variable", { fg = "#D6CFC4" })

set_hl(0, "DiffAdd", { fg = "#6B8B6B", bg = "#1A2B1A" })
set_hl(0, "DiffChange", { fg = "#7B7B6B", bg = "#252520" })
set_hl(0, "DiffDelete", { fg = "#8B6B6B", bg = "#2B1A1A" })
set_hl(0, "DiffText", { fg = "#8B8B7B", bg = "#2B2B20", bold = true })
